# Generated by Django 5.2 on 2026-07-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.TextField(choices=[('init', 'Запущен'), ('in_progress', 'Стартовал'), ('finished', 'Закончен')], default='init'),
        ),
    ]
